apiVersion: monitoring.coreos.com/v1
kind: AlertmanagerConfig
metadata:
  name: main-alertmanager-config
  namespace: monitoring
spec:
  route:
    group_by: ['alertname', 'job']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
    receiver: 'slack'
    routes:
      - match:
          severity: critical
        receiver: 'slack'
  receivers:
    - name: 'slack'
      slackConfigs:
      - apiURL:
          name: alertmanager-slack-webhook
          key: slack_webhook_url
        channel: '#alerts'
        sendResolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
  inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'namespace']