apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: monitoring
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: alertmanager-slack-webhook
    creationPolicy: Owner
  data:
    - secretKey: slack_webhook_url
      remoteRef:
        key: eks-blizzard/slack-webhook
        property: slack_webhook_url
  templates:
    - templateFrom:
        - name: "alertmanager.yaml"
          template: |
            global:
              resolve_timeout: 5m
            route:
              group_by: ['alertname', 'job']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
              receiver: 'slack'
              routes:
                - match:
                    severity: critical
                  receiver: 'slack'
            receivers:
              - name: 'slack'
                slack_configs:
                - api_url: '{{ .slack_webhook_url }}'
                  channel: '#alerts'
                  send_resolved: true
                  title: '{{ `{{` }} template "slack.default.title" . {{ `}}` }}'
                  text: '{{ `{{` }} template "slack.default.text" . {{ `}}` }}'
            inhibit_rules:
              - source_match:
                  severity: 'critical'
                target_match:
                  severity: 'warning'
                equal: ['alertname', 'namespace']