apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-monitoring
  namespace: monitoring
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::163459217187:role/eks-blizzard-us-east-1-external-secrets
---
# Use the existing service account for the External Secret
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: monitoring
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-monitoring