apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-creds-sync
  namespace: {{ .Release.Namespace }} # monitoring namespace
  labels:
    # Add labels consistent with the monitoring chart if needed
    app.kubernetes.io/component: grafana
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    # Target the K8s secret name that the chart expects
    name: grafana-admin-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/component: grafana
  # Use dataFrom to sync keys directly
  dataFrom:
    - extract:
        # Use the fixed secret prefix
        key: eks-blizzard/grafana-admin 