apiVersion: batch/v1
kind: Job
metadata:
  name: install-prometheus-crds
  namespace: {{ .Release.Namespace }}
  annotations:
    # This is what makes this resource a Job
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      name: install-prometheus-crds
    spec:
      serviceAccountName: {{ .Release.Name }}-kube-operator
      restartPolicy: OnFailure
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Create a temporary directory for the CRDs
          TMP_DIR=$(mktemp -d)
          cd $TMP_DIR
          
          echo "Downloading Prometheus CRDs..."
          # Download the CRDs from the official prometheus-operator repository
          curl -s -o crd-bundle.yaml https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
          curl -s -o tmp.yaml https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml && cat tmp.yaml >> crd-bundle.yaml
          curl -s -o tmp.yaml https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml && cat tmp.yaml >> crd-bundle.yaml
          curl -s -o tmp.yaml https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml && cat tmp.yaml >> crd-bundle.yaml
          curl -s -o tmp.yaml https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml && cat tmp.yaml >> crd-bundle.yaml
          curl -s -o tmp.yaml https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml && cat tmp.yaml >> crd-bundle.yaml
          curl -s -o tmp.yaml https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml && cat tmp.yaml >> crd-bundle.yaml
          curl -s -o tmp.yaml https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml && cat tmp.yaml >> crd-bundle.yaml
          rm tmp.yaml
          
          echo "Processing CRDs..."
          # Remove large annotations that cause the 'too long' error
          sed -i 's/helm.sh\/hook:.*//' crd-bundle.yaml
          
          echo "Installing CRDs..."
          # Apply the CRDs using server-side apply to avoid client-side validation issues
          kubectl apply --server-side -f crd-bundle.yaml
          
          echo "CRDs installed successfully"