apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.global.region | default "us-east-1" }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-monitoring
            namespace: {{ .Release.Namespace }}