apiVersion: audit.k8s.io/v1
kind: Policy
metadata:
  name: security-audit-policy
rules:
# Log all requests at the Metadata level.
- level: Metadata
  # The following requests are high volume and low risk, exclude them from audit logs
  omitStages:
    - "RequestReceived"
  users: ["system:kube-proxy", "system:kube-controller-manager", "system:kube-scheduler", "system:serviceaccount:kube-system:aws-node"]
  userGroups: ["system:nodes"]
  verbs: ["get", "list", "watch"]
  resources:
    - group: "" # core
      resources: ["endpoints", "services", "services/status", "nodes", "nodes/status"]
    - group: "discovery.k8s.io"
      resources: ["endpointslices"]
  
# Log all other requests at the Request level.
- level: Request
  omitStages:
    - "RequestReceived"
  resources:
    - group: ""
      resources: ["pods"]
    - group: "apps"
      resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    - group: "batch"
      resources: ["jobs", "cronjobs"]
    - group: "rbac.authorization.k8s.io"
      resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    - group: "policy"
      resources: ["podsecuritypolicies"]
    - group: "networking.k8s.io"
      resources: ["networkpolicies"]
    - group: ""
      resources: ["secrets", "configmaps"]
  
# Log RequestResponse level for sensitive auth and modification operations
- level: RequestResponse
  resources:
    - group: "authentication.k8s.io"
      resources: ["tokenreviews"]
    - group: "authorization.k8s.io"
      resources: ["subjectaccessreviews", "selfsubjectaccessreviews", "selfsubjectrulesreviews"]
  verbs: ["create", "update", "patch", "delete"]
  
# Default catch-all rule for all other requests
- level: Metadata
  omitStages:
    - "RequestReceived"