{{- if .Values.external-secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.external-secrets.serviceAccount.name }}
            namespace: {{ .Release.Namespace }}
{{- end }}