# Global values
clusterName: eks-blizzard-us-east-1
region: us-east-1

# External Secrets configuration
external-secrets:
  enabled: true
  serviceAccount:
    create: true
    name: external-secrets
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/eks-blizzard-us-east-1-external-secrets"
  
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  # Pod affinity to run on management node group
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role
            operator: In
            values:
            - management
    tolerations:
    - key: "management"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s

# Polaris configuration
polaris:
  enabled: true
  dashboard:
    enable: true
    replicas: 1
    service:
      type: ClusterIP
  
  webhook:
    enable: true
    mutate: false
    
    nodeSelector:
      node-role: management
    
    tolerations:
    - key: "management"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  
  audit:
    enable: true
    schedule: "0 */12 * * *"  # Twice daily
    
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
    nodeSelector:
      node-role: management
    
    tolerations:
    - key: "management"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  
  config:
    checks:
      # Reliability checks
      readinessProbeMissing: danger
      livenessProbeMissing: warning
      
      # Security checks
      hostIPCSet: danger
      hostPIDSet: danger
      hostNetworkSet: warning
      privilegeEscalationAllowed: danger
      runAsRootAllowed: warning
      runAsPrivileged: danger
      notReadOnlyRootFilesystem: warning
      insecureCapabilities: danger
      
      # Resources checks
      cpuRequestsMissing: warning
      cpuLimitsMissing: warning
      memoryRequestsMissing: warning
      memoryLimitsMissing: warning

# Trivy Operator configuration
trivy-operator:
  enabled: true
  serviceAccount:
    create: true
    name: trivy-operator
  
  trivy:
    ignoreUnfixed: true
    severity: CRITICAL,HIGH
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  nodeSelector:
    node-role: management
  
  tolerations:
  - key: "management"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"