apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: security-components
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: eks-blizzard-us-east-1
        url: https://kubernetes.default.svc
        region: us-east-1
      - cluster: eks-blizzard-us-west-2
        url: https://kubernetes.default.svc
        region: us-west-2
  template:
    metadata:
      name: '{{cluster}}-security'
    spec:
      project: default
      source:
        repoURL: https://github.com/AmichaiHadad/eks_app_2.git
        targetRevision: HEAD
        path: helm-chart/security
      destination:
        server: '{{url}}'
        namespace: security
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      info:
      - name: Description
        value: Security components (External Secrets, Policies) for {{cluster}}