apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stateful-services
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: mysql
            namespace: data
            server: https://kubernetes.default.svc
          - name: elasticsearch
            namespace: data
            server: https://kubernetes.default.svc
            parameters: '{"replicas":"1", "discovery": "single-node"}'
            # Using direct custom chart with official Elasticsearch image
            # instead of Bitnami chart to avoid security config issues
          - name: fluentd
            namespace: logging
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/AmichaiHadad/eks_app_2.git
        targetRevision: main
        path: helm-chart/{{name}}
        helm:
          parameters:
          {{- if hasKey . "parameters" }}
            {{- range $key, $value := (fromJson .parameters) }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true