apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  # This is a placeholder. In production, inject the actual value via CI/CD or External Secrets
  weather-api-key: {{ .Values.weatherApiKey | default "cGxhY2Vob2xkZXI=" | quote }}