# This template creates ExternalSecret resources to sync secrets from AWS Secrets Manager
# using the External Secrets Operator.

# Create ExternalSecret for Weather API Key
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-weather-api-external-secret
  namespace: {{ .Release.Namespace }} # Deploy in the application's namespace
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    # Target the k8s secret name the deployment expects for the weather key
    name: app-secrets
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app: {{ include "app.name" . }}
  data:
  - secretKey: weather-api-key # The key within the Kubernetes Secret
    remoteRef:
      # Use ESO's find mechanism for pattern matching
      key: {{ .Values.secrets.weatherAPIPrefix | default "eks-blizzard/weather-api" | quote }}
      property: api_key
      find:
        path: tags
        # Only select secrets tagged as active
        tags:
          status: active
        # Match the name pattern
        name:
          regexp: "^{{ .Values.secrets.weatherAPIPrefix | default "eks-blizzard/weather-api" }}.*$"
---
# Create ExternalSecret for MySQL App User connection details
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-mysql-connection-eso-sync
  namespace: {{ .Release.Namespace }} # Deploy in the application's namespace
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    # Create the dedicated secret for app DB connection details in the app namespace
    name: mysql-app-creds
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app: {{ include "app.name" . }}
          role: mysql-app-credentials # Specific label
  # Sync all relevant fields for the app connection from the app user secret
  dataFrom:
  - extract:
      # Use ESO's find mechanism for pattern matching
      key: {{ .Values.secrets.mysqlAppUserPrefix | default "eks-blizzard/mysql-app-user" | quote }}
      find:
        path: tags
        # Only select secrets tagged as active
        tags:
          status: active
        # Match the name pattern
        name:
          regexp: "^{{ .Values.secrets.mysqlAppUserPrefix | default "eks-blizzard/mysql-app-user" }}.*$" 