# Custom Elasticsearch chart values
# Using official Elasticsearch image directly instead of Bitnami chart

# No need for complex security configuration - using simple deployment with security disabled
# as specified in Project_Master_Definition.md and implemented in templates/elasticsearch.yaml

# 3-Node cluster configuration with high availability
# Each node has both master and data roles as per Project_Master_Definition.md
replicas: 3
image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 8.10.4

# Resource configuration for ES nodes
resources:
  requests:
    cpu: 500m
    memory: 3Gi
  limits:
    cpu: 1
    memory: 4Gi

# Storage configuration
storage:
  storageClassName: gp2
  size: 30Gi

# Security settings - disabled as per solution in ClaudeProgress.md
security:
  enabled: false

# Node placement
nodeSelector:
  node-role: data
tolerations:
  - effect: NoSchedule
    key: role
    value: data

# Ingress configuration
ingress:
  enabled: true
  host: elasticsearch.blizzard.co.il
  certificateArn: arn:aws:acm:us-east-1:163459217187:certificate/4ff90f30-64f8-40e1-b1b3-8f13d5fac876