apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # Renaming to reflect it syncs chart passwords
  name: mysql-chart-passwords-eso-sync
  # Deploy in the same namespace as MySQL (data)
  namespace: {{ .Release.Namespace }}
  labels:
    # Add labels consistent with the MySQL chart if needed
    app: mysql
spec:
  refreshInterval: "1h" # How often to check for updates in AWS Secrets Manager
  secretStoreRef:
    # Reference the ClusterSecretStore created by Terraform
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    # Target the single secret the chart uses for passwords via existingSecret
    name: mysql-chart-credentials
    # Policy for creating the K8s Secret if it doesn't exist
    creationPolicy: Owner
    # Template allows adding labels/annotations to the created K8s Secret
    template:
      metadata:
        labels:
          # Label for potential NetworkPolicy targeting
          app: mysql
          role: mysql-credentials # Label indicating it holds credentials
  # Define how data is mapped from AWS Secrets Manager to the K8s Secret
  data:
    # Sync Root Password
    - secretKey: mysql-root-password # Key name matches secretKeys.rootPasswordKey in values.yaml
      remoteRef:
        key: eks-blizzard/mysql-root # Root password AWS secret
        property: root_password

    # Sync App User Password
    - secretKey: mysql-password # Key name matches secretKeys.userPasswordKey in values.yaml
      remoteRef:
        key: eks-blizzard/mysql-app-user # App user AWS secret
        property: password

    # REMOVED MAPPINGS FOR APP USER - those belong in the app chart's ExternalSecret

    # Map 'username' key from AWS SM secret 'eks-blizzard/mysql' to 'mysql-user' key in K8s secret
    # - secretKey: mysql-user
    #   remoteRef:
    #     key: eks-blizzard/mysql # Name of the secret in AWS Secrets Manager
    #     property: username      # Key within the AWS Secret JSON

    # # Map 'password' key from AWS SM secret 'eks-blizzard/mysql' to 'mysql-password' key in K8s secret
    # - secretKey: mysql-password
    #   remoteRef:
    #     key: eks-blizzard/mysql
    #     property: password

    # The root password and database name are no longer synced via ESO for this secret
    # # Map 'root_password' key from AWS SM secret 'eks-blizzard/mysql' to 'mysql-root-password' key in K8s secret
    # - secretKey: mysql-root-password
    #   remoteRef:
    #     key: eks-blizzard/mysql
    #     property: root_password # Key within the AWS Secret JSON storing the root password
    #
    # # Map 'database' key from AWS SM secret 'eks-blizzard/mysql' to 'mysql-database' key in K8s secret
    # - secretKey: mysql-database
    #   remoteRef:
    #     key: eks-blizzard/mysql
    #     property: database 