apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # Name of the ExternalSecret resource
  name: mysql-eso-sync
  # Deploy in the same namespace as MySQL (data)
  namespace: {{ .Release.Namespace }}
  labels:
    # Add labels consistent with the MySQL chart if needed
    app: mysql
spec:
  refreshInterval: "1h" # How often to check for updates in AWS Secrets Manager
  secretStoreRef:
    # Reference the ClusterSecretStore created by Terraform
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    # Name of the Kubernetes Secret to create/update
    name: mysql-chart-credentials
    # Policy for creating the K8s Secret if it doesn't exist
    creationPolicy: Owner
    # Template allows adding labels/annotations to the created K8s Secret
    template:
      metadata:
        labels:
          # Label for potential NetworkPolicy targeting
          app: mysql
          role: mysql-credentials
  # Define how data is mapped from AWS Secrets Manager to the K8s Secret
  data:
    # Map 'username' key from AWS SM secret 'eks-blizzard/mysql' to 'mysql-user' key in K8s secret
    - secretKey: mysql-user
      remoteRef:
        key: eks-blizzard/mysql # Name of the secret in AWS Secrets Manager
        property: username      # Key within the AWS Secret JSON

    # Map 'password' key from AWS SM secret 'eks-blizzard/mysql' to 'mysql-password' key in K8s secret
    - secretKey: mysql-password
      remoteRef:
        key: eks-blizzard/mysql
        property: password

    # The root password and database name are no longer synced via ESO for this secret
    # # Map 'root_password' key from AWS SM secret 'eks-blizzard/mysql' to 'mysql-root-password' key in K8s secret
    # - secretKey: mysql-root-password
    #   remoteRef:
    #     key: eks-blizzard/mysql
    #     property: root_password # Key within the AWS Secret JSON storing the root password
    #
    # # Map 'database' key from AWS SM secret 'eks-blizzard/mysql' to 'mysql-database' key in K8s secret
    # - secretKey: mysql-database
    #   remoteRef:
    #     key: eks-blizzard/mysql
    #     property: database 