apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # Name of the ExternalSecret resource itself
  name: mysql-creds-sync
  # Deploy in the same namespace as the MySQL chart (data)
  namespace: {{ .Release.Namespace }}
  labels:
    app: mysql
spec:
  refreshInterval: "1h"
  secretStoreRef:
    # Reference the ClusterSecretStore created by Terraform
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    # Name of the Kubernetes Secret to create/update in the 'data' namespace
    name: mysql-chart-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app: mysql
  # Use dataFrom to extract all keys from the AWS secret
  dataFrom:
  - extract:
      # Use the fixed secret prefix
      key: eks-blizzard/mysql 