apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-password-reader
  namespace: {{ .Release.Namespace }}
data:
  password-reader.sh: |
    #!/bin/bash
    # Read the password from the ESO-synced secret
    PASSWORD=$(cat /mnt/secrets/db-password)
    # Export it as environment variable
    echo "export MYSQL_PASSWORD=$PASSWORD" > /tmp/password-env
    echo "Password injected successfully" 