# MySQL Helm chart values
mysql:
  architecture: standalone # Use StatefulSet

  # Consolidate all primary node settings under this block
  primary:
    nodeSelector:
      node-role: data
    tolerations:
      - key: role
        value: data
        effect: NoSchedule
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    persistence:
      enabled: true
      storageClass: "gp3"
      size: 20Gi
    securityContext:
      fsGroup: 1001
      runAsUser: 1001
    # Use default probes which rely on internal root/probe user
    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1
    labels:
      role: mysql-primary

  # Database configuration
  auth:
    # Let chart manage root password internally
    rootPassword: ""
    database: "app_db" # Chart creates this DB
    username: "app_user" # Chart creates this user
    # Provide app user password from a K8s secret synced by ESO
    password:
      valueFrom:
        secretKeyRef:
          name: mysql-app-user-password-secret # Secret created by mysql-app-password-eso-sync
          key: mysql-password
    # Remove existingSecret and secretKeys
    # existingSecret: "..."
    # secretKeys: { ... }

    # Enable dedicated probe user, managed internally by chart
    probe:
      enabled: true
      username: "probeuser"
      # Let chart generate password

  # initdbScripts section is removed entirely

  # Service configurations
  service:
    type: ClusterIP
    port: 3306

  # Top-level security context
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

# AWS Secrets Manager details
secrets:
  # Use prefix for AWS secrets without wildcard - ESO will handle the pattern matching
  awsSecretPrefix: "eks-blizzard/mysql-app-user"
