# MySQL Helm chart values
mysql:
  architecture: standalone # Use StatefulSet

  # Consolidate all primary node settings under this block
  primary:
    nodeSelector:
      node-role: data
    tolerations:
      - key: role
        value: data
        effect: NoSchedule
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    persistence:
      enabled: true
      storageClass: "gp3"
      size: 20Gi
    securityContext:
      fsGroup: 1001
      runAsUser: 1001
    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1
    labels:
      role: mysql-primary

  # Database configuration
  auth:
    # Let the chart generate/manage the root password internally
    rootPassword: ""
    database: "app_db"
    username: "app_user"
    # Use existingSecret ONLY for the application user password
    existingSecret: "mysql-chart-credentials" # K8s secret created by ESO in 'data' namespace for app user
    secretKeys:
      userPasswordKey: mysql-password # Key within secret holding app user password
      # Do NOT specify rootPasswordKey - let chart manage root

    # Enable and configure the dedicated probe user
    probe:
      enabled: true
      username: "probeuser"
      # Let the chart generate the probe password internally by leaving this empty/uncommented
      # password: ""

  # initdbScripts section is removed entirely

  # Service configurations
  service:
    type: ClusterIP
    port: 3306

  # Top-level security context (might be needed by Bitnami chart structure)
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
