# MySQL Helm chart values
mysql:
  architecture: standalone # Use StatefulSet

  # Consolidate all primary node settings under this block
  primary:
    nodeSelector:
      node-role: data
    tolerations:
      - key: role
        value: data
        effect: NoSchedule
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    persistence:
      enabled: true
      storageClass: "gp3"
      size: 20Gi
    securityContext:
      fsGroup: 1001
      runAsUser: 1001
    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1
    labels:
      role: mysql-primary

    # Explicitly set env var for root password from the secret for probes
    extraEnvVars:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-chart-credentials # The K8s secret name created by ESO
            key: mysql-root-password   # The key within the secret holding the root password

  # Database configuration - Use existingSecret for app user AND root
  auth:
    rootPassword: "" # Let existingSecret handle root password
    database: "app_db"
    username: "app_user"
    existingSecret: "mysql-chart-credentials" # K8s secret created by ESO in 'data' namespace
    secretKeys:
      userPasswordKey: mysql-password # Key within secret holding app user password
      rootPasswordKey: mysql-root-password # Key within secret holding root password

  # initdbScripts section is removed entirely

  # Service configurations
  service:
    type: ClusterIP
    port: 3306

  # Top-level security context (might be needed by Bitnami chart structure)
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
