# Monitoring stack configuration
kube-prometheus-stack:
  # Global settings
  global:
    rbac:
      create: true
    
  # Prometheus Operator configuration
  prometheusOperator:
    enabled: true
    nodeSelector:
      node-role: monitoring
    tolerations:
      - key: monitoring
        value: "true"
        effect: NoSchedule
    admissionWebhooks:
      enabled: true
      patch:
        nodeSelector:
          node-role: monitoring
        tolerations:
          - key: monitoring
            value: "true"
            effect: NoSchedule
  
  # Prometheus configuration
  prometheus:
    enabled: true
    serviceAccount:
      create: true
    nodeSelector:
      node-role: monitoring
    tolerations:
      - key: monitoring
        value: "true"
        effect: NoSchedule
    prometheusSpec:
      replicas: 1
      retention: 15d
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: 1000m
          memory: 4Gi
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
      # Additional scrape configurations for MySQL and Elasticsearch
      additionalScrapeConfigs:
        - job_name: mysql-exporter
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                  - monitoring
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_name]
              regex: prometheus-mysql-exporter
              action: keep
        - job_name: elasticsearch-exporter
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                  - monitoring
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_name]
              regex: prometheus-elasticsearch-exporter
              action: keep
        - job_name: keda-metrics-apiserver
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                  - keda
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_name]
              regex: keda-metrics-apiserver
              action: keep
      
      # Alerting rules
      ruleSelector: {}
      ruleNamespaceSelector: {}
      ruleSelectorNilUsesHelmValues: true
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}
      serviceMonitorSelectorNilUsesHelmValues: true
      podMonitorSelector: {}
      podMonitorNamespaceSelector: {}
      podMonitorSelectorNilUsesHelmValues: true
  
  # Alertmanager configuration
  alertmanager:
    enabled: true
    nodeSelector:
      node-role: monitoring
    tolerations:
      - key: monitoring
        value: "true"
        effect: NoSchedule
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['alertname', 'job']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'slack'
        routes:
          - match:
              severity: critical
            receiver: 'slack'
      receivers:
        - name: 'slack'
          slack_configs:
          - api_url: '${slack-webhook-url}'
            channel: '#alerts'
            send_resolved: true
            title: '{{ template "slack.default.title" . }}'
            text: '{{ template "slack.default.text" . }}'
      inhibit_rules:
        - source_match:
            severity: 'critical'
          target_match:
            severity: 'warning'
          equal: ['alertname', 'namespace']
    # Use external secret for Slack webhook
    alertmanagerConfigFromSecret:
      enabled: true
      name: "alertmanager-slack-webhook"
      key: "alertmanager.yaml"
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
  
  # Grafana configuration
  grafana:
    enabled: true
    nodeSelector:
      node-role: monitoring
    tolerations:
      - key: monitoring
        value: "true"
        effect: NoSchedule
    adminPassword: "admin-password-placeholder"  # Will be overridden by External Secrets
    persistence:
      enabled: true
      storageClassName: gp3
      size: 10Gi
    ingress:
      enabled: true
      ingressClassName: alb
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
        alb.ingress.kubernetes.io/ssl-redirect: "443"
        # ACM certificate ARN will be added here
        # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:...
      hosts:
        - grafana.blizzard.co.il
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-operated:9090
          access: proxy
          isDefault: true
        - name: Elasticsearch
          type: elasticsearch
          url: http://elasticsearch-master:9200
          access: proxy
          database: k8s-logs-*
          jsonData:
            timeField: "@timestamp"
            esVersion: 70
            logLevelField: level
            logMessageField: log
  
    # Dashboards configuration
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
    
    # Pre-installed dashboards
    dashboards:
      default:
        # Make sure all dashboard IDs and revisions are strings to avoid label issues
        kubernetes-cluster:
          gnetId: "7249"  # Quoted to ensure string type
          revision: "1"   # Quoted to ensure string type 
          datasource: Prometheus
        mysql-overview:
          gnetId: "7362"  # Quoted to ensure string type
          revision: "1"   # Quoted to ensure string type
          datasource: Prometheus
        elasticsearch:
          gnetId: "6483"  # Quoted to ensure string type
          revision: "1"   # Quoted to ensure string type
          datasource: Prometheus
        node-exporter:
          gnetId: "1860"  # Quoted to ensure string type
          revision: "22"  # Quoted to ensure string type
          datasource: Prometheus
  
  # Kube state metrics
  kubeStateMetrics:
    enabled: true
    nodeSelector:
      node-role: monitoring
    tolerations:
      - key: monitoring
        value: "true"
        effect: NoSchedule
  
  # Node exporter
  nodeExporter:
    enabled: true
    tolerations:
      - operator: Exists
  
  # Thanos ruler for long-term query
  thanosRuler:
    enabled: false
  
  # Default values for Prometheus rules
  defaultRules:
    create: true
    appNamespace:
      rule:
        enabled: true
    rules:
      alertmanager: true
      etcd: true
      general: true
      k8s: true
      kubeApiserver: true
      kubePrometheusNodeAlerting: true
      kubePrometheusNodeRecording: true
      kubernetesAbsent: true
      kubernetesApps: true
      kubernetesResources: true
      kubernetesStorage: true
      kubernetesSystem: true
      kubeScheduler: true
      network: true
      node: true
      prometheus: true
      time: true

# MySQL exporter
prometheus-mysql-exporter:
  mysql:
    host: "mysql.data"
    port: 3306
    user: "prometheus"
    pass: "prometheus-exporter-password-placeholder"  # Will be overridden by External Secrets
    db: "app_db"
  
  nodeSelector:
    node-role: monitoring
  
  tolerations:
    - key: monitoring
      value: "true"
      effect: NoSchedule
  
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  
  serviceMonitor:
    enabled: true

# Elasticsearch exporter
prometheus-elasticsearch-exporter:
  es:
    uri: http://elasticsearch-master:9200
    all: true
    indices: true
    indices_settings: true
    cluster_settings: true
    ssl:
      enabled: false
  
  nodeSelector:
    node-role: monitoring
  
  tolerations:
    - key: monitoring
      value: "true"
      effect: NoSchedule
  
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  
  serviceMonitor:
    enabled: true