apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: monitoring-us-east-1
            cluster: eks-blizzard-us-east-1
            url: https://kubernetes.default.svc
            region: us-east-1
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/AmichaiHadad/eks_app_2.git
        targetRevision: main
        path: helm-chart/monitoring
        helm:
          valueFiles:
            - values.yaml
          parameters:
            - name: grafana.ingress.hosts[0]
              value: 'grafana.{{region}}.blizzard.co.il'
            - name: grafana.ingress.annotations
              value: |
                kubernetes.io/ingress.class: alb
                alb.ingress.kubernetes.io/scheme: internet-facing
                alb.ingress.kubernetes.io/target-type: ip
                alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
                alb.ingress.kubernetes.io/ssl-redirect: "443"
                alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:163459217187:certificate/4ff90f30-64f8-40e1-b1b3-8f13d5fac876
                external-dns.alpha.kubernetes.io/hostname: grafana.{{region}}.blizzard.co.il
                external-dns.alpha.kubernetes.io/ttl: "300"
            - name: clusterName
              value: 'eks-blizzard-{{region}}'
            - name: global.region
              value: '{{region}}'
            - name: externalDNS.serviceAccount.annotations."eks\.amazonaws\.com/role-arn"
              value: 'arn:aws:iam::163459217187:role/eks-blizzard-{{region}}-route53-dns-manager-irsa'
      destination:
        server: '{{url}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
          - Replace=false
          - SkipDryRunOnMissingResource=true