apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mysql-service
  namespace: argocd
spec:
  # Use list generator instead of configMap generator
  generators:
    - list:
        elements:
          - name: mysql
            namespace: data
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/AmichaiHadad/eks_app_2.git
        targetRevision: main
        path: helm-chart/{{name}}
        helm:
          values: |
            # AWS Secrets Manager configuration
            secrets:
              # Use prefix for pattern matching
              awsSecretPrefix: "eks-blizzard/mysql-app-user"
            
            # MySQL auth configuration
            mysql:
              auth:
                # Use our existing secret with both formats
                existingSecret: "mysql-app-user-password-secret"
                # Keys in kebab-case format that the chart will map to environment variables
                secretKeys:
                  root: "mysql-root-password"
                  password: "mysql-password"
              # Primary node configuration
              primary:
                # Additional direct mapping of secret to environment variables
                extraEnvVarsSecret: "mysql-app-user-password-secret"
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true 