apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mysql-service
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: mysql
            namespace: data
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/AmichaiHadad/eks_app_2.git
        targetRevision: main
        path: helm-chart/{{name}}
        helm:
          values: |
            secrets:
              # Use the full ARN for the AWS Secret Manager secret
              mysqlAppUserAwsSecretName: "arn:aws:secretsmanager:us-east-1:163459217187:secret:mysql-app-user-secret"
            
            mysql:
              auth:
                password: ""
                existingSecret: "mysql-app-user-password-secret"
                secretKeys:
                  password: "mysql-password"
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true 