apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mysql-service
  namespace: argocd
spec:
  # Use the configMapGenerator to dynamically get the secret name
  generators:
    - configMap:
        name: terraform-secret-outputs
        namespace: argocd
        labelSelector:
          matchLabels:
            app.kubernetes.io/part-of: external-secrets
  template:
    metadata:
      name: mysql
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/AmichaiHadad/eks_app_2.git
        targetRevision: main
        path: helm-chart/mysql
        helm:
          values: |
            # Set the MySQL secret name from Terraform output via ConfigMap
            secrets:
              mysqlAppUserSecretName: "{{values.mysql_secret_name}}"
              mysqlAppUserAwsSecretName: "{{values.mysql_secret_name}}"
            
            # MySQL auth configuration
            mysql:
              auth:
                password: ""
                existingSecret: "mysql-app-user-password-secret"
                secretKeys:
                  password: "mysql-password"
      destination:
        server: https://kubernetes.default.svc
        namespace: data
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true 