apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mysql-service
  namespace: argocd
spec:
  # Use list generator instead of configMap generator
  generators:
    - list:
        elements:
          - name: mysql
            namespace: data
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/AmichaiHadad/eks_app_2.git
        targetRevision: main
        path: helm-chart/{{name}}
        helm:
          values: |
            # AWS Secrets Manager configuration
            secrets:
              # Use prefix for pattern matching
              awsSecretPrefix: "eks-blizzard/mysql-app-user"
            
            # MySQL auth configuration
            mysql:
              auth:
                # Set a secure root password directly
                rootPassword: "change-me-now-random-123!"
                # Use a dummy password - actual password will come from ExternalSecret
                password: "dummy-placeholder-replaced-by-secret"
                # Database and user settings
                database: "app_db"
                username: "app_user"
              
              # Setup password injection
              primary:
                # Additional volumes to mount secrets
                extraVolumes:
                  - name: password-secret
                    secret:
                      secretName: mysql-app-user-password-secret
                  - name: scripts-volume
                    configMap:
                      name: mysql-password-reader
                
                # Mount the volumes
                extraVolumeMounts:
                  - name: password-secret
                    mountPath: /mnt/secrets
                    readOnly: true
                  - name: scripts-volume
                    mountPath: /mnt/scripts
                    readOnly: true
                
                # Init container to read the password
                initContainers:
                  - name: password-injector
                    image: bitnami/minideb:latest
                    command: ["/bin/bash", "-c"]
                    args:
                      - source /mnt/scripts/password-reader.sh
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true 