apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mysql-service
  namespace: argocd
spec:
  # Use list generator instead of configMap generator
  generators:
    - list:
        elements:
          - name: mysql
            namespace: data
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/AmichaiHadad/eks_app_2.git
        targetRevision: main
        path: helm-chart/{{name}}
        helm:
          values: |
            # AWS Secrets Manager configuration
            secrets:
              # Use prefix for pattern matching
              awsSecretPrefix: "eks-blizzard/mysql-app-user"
            
            # MySQL auth configuration
            mysql:
              auth:
                # Set a secure root password directly
                rootPassword: "change-me-now-random-123!"
                # Get the app user password from our secret 
                password:
                  valueFrom:
                    secretKeyRef:
                      name: mysql-app-user-password-secret
                      key: db-password
                # Database and user settings
                database: "app_db"
                username: "app_user"
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true 