apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stateful-services
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - name: mysql
                  namespace: data
                  chart: mysql
                - name: elasticsearch
                  namespace: data
                  chart: elasticsearch
                - name: fluentd
                  namespace: logging
                  chart: fluentd
          - list:
              elements:
                - cluster: eks-blizzard-us-east-1
                  url: https://kubernetes.default.svc
                  region: us-east-1
                - cluster: eks-blizzard-us-west-2
                  url: https://kubernetes.default.svc
                  region: us-west-2
  template:
    metadata:
      name: '{{name}}-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/your-org/eks-gitops.git
        targetRevision: main
        path: helm-chart/{{chart}}
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true