apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stateful-services
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: mysql
            namespace: data
            server: https://kubernetes.default.svc
          - name: elasticsearch
            namespace: data
            server: https://kubernetes.default.svc
            # Using direct custom chart with official Elasticsearch image
            # instead of Bitnami chart to avoid security config issues
          - name: fluentd
            namespace: logging
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/AmichaiHadad/eks_app_2.git
        targetRevision: main
        path: helm-chart/{{name}}
        helm:
          parameters:
            # Only pass mysql secret name param if the app is mysql
            {{- if eq .name "mysql" }}
            - name: secrets.mysqlAppUserAwsSecretName
              value: '{{ .values.mysql_app_user_aws_secret_name }}'
            {{- end }}
            # Add parameters for Elasticsearch
            {{- if eq .name "elasticsearch" }}
            - name: replicas
              value: "3"
              forceString: true
            - name: discovery
              value: "multi-node"
            {{- end }}
            # Add other specific parameters here if needed for Fluentd later
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true