apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: app
    kind: Deployment
  minReplicaCount: 2
  maxReplicaCount: 10
  pollingInterval: 15
  cooldownPeriod: 60
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.monitoring.svc.cluster.local:9090
      metricName: http_requests_per_second
      threshold: '10'
      query: sum(rate(http_requests_total{app="app"}[5m]))